name: Generate Blog Index

on:
  push:
    paths:
      - 'cerita/**'
      - 'generate_index.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run generate_index.py
        run: |
          python generate_index.py

      - name: Commit and push index.html files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index*.html
          git commit -m "Generate index.html automatically" || echo "No changes"
          git push
