name: Generate Blog and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Workflow akan berjalan setiap kali ada push ke branch 'main'
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Bisa '3.9', '3.10', dll.

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown # Pastikan 'markdown' terinstal

      - name: Run Python script to generate HTML
        run: python generate_blog.py # Nama file Python yang baru

      - name: Deploy to GitHub Pages
        # Action ini akan secara otomatis melakukan git commit dan push dari direktori yang ditentukan
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Ini HARUS sesuai dengan OUTPUT_DIR di skrip Python Anda
          # Jika Anda ingin membersihkan file-file lama di GitHub Pages, tambahkan `keep_files: false`
          # keep_files: false
